[package]
name = "songsonar"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = [ "tls" ] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "postgres", "macros", "chrono", "uuid", "migrate" ] }
tokio = { version = "1", features = ["rt", "process"] }
uuid = { version = "0.8", features = [ "serde", "v4" ] }
chrono = { version = "0.4", features = [ "serde" ] }
log = "0.4"
pretty_env_logger = "0.4"
thiserror = "1"
anyhow = "1"
aspotify = "0.7.0"
